spring:
  middleground:
    netty:
#      inet-host: 192.168.17.221
#      inet-port: 4923
#      inet-path: middleground-on-cloud-heartbeat-server
      inet-host: 124.222.48.62 # 服务端地址
      inet-port: 30676 #服务端端口
      inet-path: middleground-on-cloud-heartbeat-server
      client-id: local # 客户端ID
  data:
    redis:
      host: 192.168.17.221
      port: 30553
      password: laihui
      database: 2

