spring:
  datasource:
    url: jdbc:mysql://124.222.48.62:30512/wu_lazy_cloud_netty_server?allowMultiQueries=true&useUnicode=true&autoReconnect=true&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&databaseTerm=SCHEMA
    username: root
    password: wujiawei
    driver-class-name: com.mysql.cj.jdbc.Driver
